import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          border: "2px solid black",
          borderRadius: "1rem",
          margin: "4rem",
        }}
        className="header"
      >
        <div style={{display: "flex", justifyContent: "space-around"}} className="lead">
          <Link href={`/`}>Home</Link>
          <Link href={`/playerslist`}>Players List</Link>
          <Link href={`/createnew`}>Create New</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
